import React from 'react';
import ArrowBackSharpIcon from '@material-ui/icons/ArrowBackSharp';
import AppBar from '@material-ui/core/AppBar';
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import IconButton from '@material-ui/core/IconButton';

function BusinessPolicy() {
  return (
    <div>
    <AppBar position="static" color="inherit">
        <Toolbar>
          <IconButton edge="start" color="disabled" aria-label="back" onClick={() => {
            console.log('go back')
            if (window.TestAndroid) {
              window.TestAndroid.goBackToApa(true)
            }
            if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.goBackToApa) {
              window.webkit.messageHandlers.goBackToApa.postMessage(true);
            }
          }
          }>
            <ArrowBackSharpIcon />
          </IconButton>
      <Typography className="main-header">BUSINESS POLICY</Typography>
          

        </Toolbar>
      </AppBar>
      
    <div className="terms">
    
      {/* <h1>Business Policy</h1> */}
      <p> Welcome! This document is generated by electronic system which contains electronic record in terms of Information Technology Act 2000.This record contains rules and regulations and Terms and Use for the usage of the official website of www.nextdoorhub.com that are published in accordance with provisions of Rule 3 (1) of the Information Technology (intermediate guidelines) Rules, 2011. When you use the NextDoorHub website, you are to follow the Terms of Use of NextDoorHub. The website domain name www.nextdoorhub.com is owned by Senrysa Technologies Private limited. The mobile application ‘NextDoorHub’ is owned by Senrysa Technologies Private Limited. The website, contents, products, services and tools are guided and governed by the Terms of Use i.e. the Terms and Conditions by Senrysa Technologies Private Limited and this means you are binding obligations with NextDoorHub. In the Terms of Use, the usage of the word “You” and / or “User” means a natural person or a legal person who has visited the official website of NextDoorHub and also who has agreed to become a buyer by providing the registration data and becoming a Registered User. The term “We”, “Us”, “Our” on the context of Terms of Use means the regulatory body of NextDoorHub and Senrysa Technologies Private Limited. When you use any of the services or any products or tools provided by NextDoorHub that means you are subjected to the guidelines, terms and conditions that are applicable to such products and services included under the Terms of Use. We at our sole decision and discretion can change, add, modify or remove portions or whole of the Terms and Conditions, without any prior notice to the user. The user, i.e. you have to view the Terms of Use time to time to have a constant check on the changes made or any updates announced. Your use of the official website of NextDoorHub means that you accept and agree to the Terms and Conditions. This also implies that you have agreed and accepted the changes that are made in the Terms of Use. You are granted personal, non-transferable, non-exclusive and limited privilege to enter, access and use the website as long as you comply with the Terms of Use. </p>
      <ul>
        <li><b>Eligibility for Membership</b>
          <p> Persons eligible to access the website are those who can form legally binding contracts under Indian Contract Act, 1872. Under this contract, persons who are “incompetent to contract” includes minors, un-discharged insolvents etc. A minor below the age of 18 years shall not register as user of NextDoorHub. An 18 year old or below shall not do the transaction on the website of NextDoorHub. A minor’s parents or legal guardian can however do the transaction on behalf of him / her. NextDoorHub has the right to deny the access of the website and terminate the registration or membership if it is discovered that the transaction has been done by a minor below the age of 18 years. </p>
        </li>
        <li><b>Services Offered</b>
          <p> NextDoorHub is an ecommerce platform where numerous goods are sold under various categories. The online shopping services enable us to buy these items which are collectively called “Product” or “products”. The products are also supervised and functional according to the Purchase Policy, Cancellation Policy, Return and Replacement Policy, FAQ and other terms and conditions available on the website. Moreover, there might be specific Terms of Use for specific products which will be displayed along with the product. However, NextDoorHub does not give warranty that the product description of the product is accurate, reliable or error-free as these information are always provided by the sellers. It assumes no liability in this regard. </p>
        </li>
        <li><b>Usage of the website</b>
          <p>The following pictures, texts, and contents shall be refrained from uploading, displaying, hosting, and updating:</p>
          <ul>
            <li>If the pictures, texts, and content belongs to someone else and you have no right over it.</li>
            <li>If the pictures, texts, and content is misleading</li>
            <li>If the pictures, texts, and content is harassing, derogatory, pornographic, paedophilic, sexist, hateful, directly or indirectly relates to anything unlawful in any manner, including Indecent Representation of Women (Prohibition) Act, 1986.</li>
            <li>If it directly or indirectly harasses a person or a community.</li>
            <li>If it promotes or encourages any criminal activities, illegal activities, threatening messages and abusive contents.</li>
            <li>If it involves ‘junk mails’, ‘spamming’, ‘chain letters’, mass mailing etc.</li>
            <li>If it infringes any third party’s rights which includes rights of privacy, rights of publicity, intellectual property rights etc.</li>
            <li>If it contains images of another person</li>
            <li>If it contains hidden pages, hidden images, password-only access pages etc.</li>
            <li>If it contains or promotes any unauthorized copy of other copyrighted work.</li>
            <li>If it refers to any website which to our sole discretion which contains inappropriate contents, images and videos.</li>
            <li>User/users may be considered fraudulent due to fraudulent activities if they are found to meet the following scenarios:</li>
            <li>Users don’t produce required adequate documents and information during the verification of payment details.</li>
            <li>Users provide invalid email address and phone number.</li>
            <li>User refuses to pay for any order purchased</li>
            <li>User is not replying to payment verification mail that’s been sent by NextDoorHub.</li>
          </ul>
        </li>
        <li><b>Contents Posted on Website</b>
          <p> Content here refers to the displayed texts, images, graphics, logos, trademarks, sounds, visual interfaces, music, and artwork. All the contents are third party user generated contents. NextDoorHub has no control over third party content that are user generated. You may access and download the product information, services and contents that are available on the website platform, provided that you: </p>
          <ul>
            <li>Will not make any modifications to the content</li>
            <li>Shall only use this content for personal and non-commercial use. The contents should not be copied and posted on any social network or the internet and shall also not be broadcast on any media platform.</li>
            <li> Will not remove any proprietary notice language in all copies of the text, document and content. </li>
            <li>Will not make any additional warranties to such content and documents</li>
          </ul>
        </li>
        <li><b>Privacy</b>
          <p> NextDoorHub ensures a complete protection of your privacy. We understand the importance of the customers and users’ privacy of personal information shared with us. However, the information may be shared with our other corporate entities and affiliates. We process and we store your personal information and information regarding payment and any sensitive information or data collected as defined under Information Technology Act 2000 and Rules there under. We may disclose the information only if required by law or when the disclosure is of utmost necessity for responding to court orders, subpoenas or other legal process. </p>
        </li>
        <li><b>Disclaimer of Warranties and Liability:</b>
          <p> The products and contents available here on the platform are provided on “as is” and “as available” basis with no representation or warranties implied except otherwise specified in writing. All the products sold on the website or platform are governed by state laws that differs in every state, and if the seller fails to deliver the products due to the implication of the different State Laws, the seller will return the amount or will give credit for the amount received in advance of the products that could not be delivered to you. </p>
        </li>
        <li><b>Selling</b>
          <p> To be a seller you have to register to NextDoorHub. After being a registered seller, you have to abide by the policies and Terms of Use. You are able to sell product(s) that you have listed for sale on the website of NextDoorHub. All the items listed must be arranged and listed in the appropriate category on the website of NextDoorHub. You must declare and ensure that the products and items you have listed for sale on our website do not infringe upon intellectual property, privacy rights of third parties, trade secret or other proprietary rights. The listed items or products must be kept in stock for the successful fulfilment of sales. The contents must not be misleading and must provide the accurate description of the product(s). You must agree to refund any amounts received from the buyer, in case your product description do not match the actual product(s) or condition of the product(s). You must not list a single product in multiple quantities across various categories on the website. NextDoorHub has the right to delete the listing of one single product listed on various categories on the website. </p>
        </li>
        <li><b>Trademark and Copyright:</b>
          <p> The items and products sold on NextDoorHub including images, graphics, texts, contents, audio clips and video clips are protected by copyrights, trademarks and other intellectual property rights. All products are a third party user generated material that are controlled and operated by NextDoorHub. You may access and download the product information, services and the contents that are available on the website platform, provided that you will not make any modifications to the content or you must not copy, reproduce, upload or distribute the materials in any way or any means without the consent of the owner, seller and authorities of the website, otherwise it will be considered the violation of copyrights, trademarks and other intellectual property rights. The products and contents available on NextDoorHub are solely for your personal and non-commercial use. </p>
        </li>
        <li><b>Limitation of Liability:</b>
          <p>NextDoorHub, shall be in no way, liable for any punitive, incidental, consequential or indirect damages due to:</p>
          <ul>
            <li>Breach of condition, representations of warranties by the manufacturers of the products</li>
            <li>The use of services or products</li>
            <li>The inability to use the services or products</li>
            <li>The unauthorized access to or alteration of the user’s transmissions or data</li>
            <li>NextDoorHub shall not be responsible for non-availability of NextDoorHub during any periodic maintenance operations on any unplanned suspension of access to the NextDoorHub. The Users must agree that any product or data or content downloaded at NextDoorHub is done at users’ own discretion and risk and shall be solely responsible for any loss of data or any damage in phone due to download of data or content.</li>
          </ul>
        </li>
        <li><b>Termination</b>
          <p> NextDoorHub has the rights to terminate or suspend any service or your overall use of NextDoorHub if it believes in its absolute discretion that you have violated, abused, infringed or exploited any terms of Service. The termination or suspension of account and usage of NextDoorHub will also be executed if you use any false email address, provide any false information or use the website for any unlawful or fraudulent purpose. </p>
        </li>
        <li><b>Disclaimer</b>
          <p> You consider, acknowledge the fact that you are accessing and visiting the website, the platform and the services on the platform. You also undertake that you are transacting at your own risk. We shall not be liable or responsible for any actions or inactions of sellers nor any warranties by the sellers and manufacturers of the products. We also disclaim responsibility and any liability and warranties or representations in respect of quality, accuracy, performance, fitness, suitability of any product listed on the website. </p>
        </li>
      </ul>
    </div>
    </div>
  );
}

export default BusinessPolicy;